### ISSUE TITLE
Code stopped working

### ISSUE THREAD

**Issue by sathwikrao575** [crunchprank/google-sheets-to-html#8]
I'm not able to figure out why. I use this code a lot please update
<img width="333" alt="chrome_08jLHMGxDX" src="https://user-images.githubusercontent.com/6828692/88454117-a064f100-ce8a-11ea-9359-f13aa6a8fd41.png">

**Comment by crunchprank** [comment]
Thanks for reporting this. I am also able to reproduce it on my end. I'm looking into it.

**Comment by thomasbonsirven** [comment]
Hello,

Yes i have same problem,
Please, look on your example : https://dev.crunchprank.net/google-sheets-to-html/

The problem is due to CORS.
![image](https://user-images.githubusercontent.com/18753454/93054581-d132fc80-f669-11ea-9772-df267fbc58aa.png)

But i dont how to resolve this, for the moment..
Please, help us

**Comment by crunchprank** [comment]
Have a fix incoming. Will be updated tomorrow.

**Comment by crunchprank** [comment]
Fixed in 4fd7b90.
